export const data =
    [
        { question: "The thing you <3 the most (after me)", answer: "BASKETBALL" },
        { question: "Your team", answer: "SOUTHSIDESAINTS" },
        { question: "Something you're a master at", answer: "DIGITALECONOMY" },
        { question: "Fave singer", answer: "SADE" },
        { question: "One word to describe you", answer: "CUTE" },
        { question: "Two words to describe you", answer: "SOCUTE" },
        { question: "Star sign", answer: "TAURUS" },
        { question: "Your catchphrase", answer: "YOUKNOWWHATIMSAYIN" },
        { question: "Fave food", answer: "MASSAMAN" },
        { question: "A fear", answer: "Allegators" },
        { question: "Coffee order", answer: "FLATWHITE" },
        { question: "Work name", answer: "MRSIMPSON" },
        { question: "Your real enthincity", answer: "INDIAN" },
        { question: "Cutest job you've had", answer: "BALLERBABIES" },
        { question: "Band who released a massive hit album on the day you were born", answer: "BACKSTREETBOYS" },
        { question: "Day of the week you were born", answer: "TUESDAY" },
        { question: "Your favourite colour", answer: "PINK" },
        { question: "Your chinese Zodiac", answer: "RABBIT" },
        { question: "Your generation", answer: "GENZ" },
        { question: "No.1 song day you were born", answer: "LIVINDAVIDALOCA" },
        { question: "Your fave holiday you've been on", answer: "BRAZIL" },
        ///
        { question: "Fave player", answer: "STEPHENCURRY" },
        { question: "Best meal of yours (to me)", answer: "HAINANCHICKEN" },
        { question: "If you were to do a quiz on this topic you'd win", answer: "GEOGRAPHY" },
        { question: "Trip of your birthday present", answer: "LAKEDISTRICT" },
        { question: "Your dream job", answer: "ASTRONAUT" },
        { question: "Your dream job", answer: "ASTRONAUT" },
        { question: "Your dream job", answer: "ASTRONAUT" },
        { question: "Your dream job", answer: "ASTRONAUT" },
        { question: "Your dream job", answer: "ASTRONAUT" },
        { question: "Your dream job", answer: "ASTRONAUT" },
         { question: "Your dream job", answer: "ASTRONAUT" },
      
    ]
